### ISSUE TITLE
Feature request: a REPL server using asyncio

### ISSUE THREAD

**Issue by gjcarneiro** [vxgmichel/python3-apython#1]
Cool project!

If I can make a suggestion, add a REPL server module.  Something similar to [eventlet's backdoor module](http://eventlet.net/doc/modules/backdoor.html).  It listens on a TCP port, and you can connect to it (I usually run `rlwrap nc localhost <port>`), and execute Python commands. That is super useful for debugging server applications!

You can find the eventlet code [here](https://github.com/eventlet/eventlet/blob/master/eventlet/backdoor.py).

**Comment by vxgmichel** [comment]
Thanks!

I didn't know about this `eventlet.backdoor` module but it is very similar to what I already wrote. So you can already serve  a python interpreter by running the following line somewhere in your code:
```python
server = await apython.start_interactive_server(
    apython.AsynchronousConsole, host='', port=8888)
```
I'm even considering making `apython.AsynchronousConsole` the default `factory` argument so it can be started using:
```python
server = await apython.start_interactive_server(port=8888)
```

**Comment by gjcarneiro** [comment]
Ah, nice.  Yes, a simple `apython.start_interactive_server` function would be nice.  

Just make sure that `host` defaults to `localhost`, please.  I'm not sure what empty string as `host` value means, but if it means the same as `0.0.0.0` then it's a dangerous default IMHO.

**Comment by vxgmichel** [comment]
You're right, it's been fixed. I also added a `--serve` option to the `apython` script, so it is possible to add a backdoor without modifying the code:

```bash
$ apython --serve localhost:8888 -m some.asyncio.project --some --options
```
More info in the [`Serving the console`](https://github.com/vxgmichel/python3-apython#serving-the-console) section of the readme file.

Thanks for your feedback!
